name: CI/CD Pipeline for Pigsty using makefile

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bash:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run makefile
        run: |
         make deps